/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gestionnotes;

import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Query;
import java.util.List;

import com.formdev.flatlaf.FlatDarkLaf;
import java.awt.Color;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.*;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

import org.jasypt.util.text.BasicTextEncryptor;


/**
 *
 * @author HP
 */
public class AddUser extends javax.swing.JFrame {

    /**
     * Creates new form AddUser
     */
    public AddUser() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BodyPanel = new javax.swing.JPanel();
        userFormPanel = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        fullnameField = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        emailField = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        PasswordField = new javax.swing.JPasswordField();
        jSeparator3 = new javax.swing.JSeparator();
        AddUserBtn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        CloseBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(300, 190));
        setMinimumSize(new java.awt.Dimension(1320, 700));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BodyPanel.setBackground(new java.awt.Color(45, 50, 80));
        BodyPanel.setMinimumSize(new java.awt.Dimension(1320, 700));
        BodyPanel.setPreferredSize(new java.awt.Dimension(1320, 700));
        BodyPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        userFormPanel.setBackground(new java.awt.Color(66, 71, 105));
        userFormPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(66, 71, 105), 0, true));
        userFormPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(103, 111, 157));
        jLabel10.setText("Name");
        userFormPanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 130, -1));

        fullnameField.setBackground(new java.awt.Color(66, 71, 105));
        fullnameField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        fullnameField.setForeground(new java.awt.Color(255, 255, 255));
        fullnameField.setToolTipText("");
        fullnameField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        fullnameField.setCaretColor(new java.awt.Color(255, 255, 255));
        fullnameField.setMargin(new java.awt.Insets(2, 2, 0, 2));
        userFormPanel.add(fullnameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 390, 40));

        jSeparator1.setBackground(new java.awt.Color(249, 177, 122));
        jSeparator1.setForeground(new java.awt.Color(249, 177, 122));
        userFormPanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 390, 10));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(103, 111, 157));
        jLabel3.setText("Email");
        userFormPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 130, -1));

        emailField.setBackground(new java.awt.Color(66, 71, 105));
        emailField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        emailField.setForeground(new java.awt.Color(255, 255, 255));
        emailField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        emailField.setCaretColor(new java.awt.Color(255, 255, 255));
        userFormPanel.add(emailField, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 390, 40));

        jSeparator2.setBackground(new java.awt.Color(249, 177, 122));
        jSeparator2.setForeground(new java.awt.Color(249, 177, 122));
        userFormPanel.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 390, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(103, 111, 157));
        jLabel4.setText("Password");
        userFormPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 150, -1));

        PasswordField.setBackground(new java.awt.Color(66, 71, 105));
        PasswordField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        PasswordField.setForeground(new java.awt.Color(255, 255, 255));
        PasswordField.setText("jPasswordField1");
        PasswordField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        PasswordField.setCaretColor(new java.awt.Color(255, 255, 255));
        userFormPanel.add(PasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 390, 40));

        jSeparator3.setBackground(new java.awt.Color(249, 177, 122));
        jSeparator3.setForeground(new java.awt.Color(249, 177, 122));
        userFormPanel.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 390, -1));

        AddUserBtn.setBackground(new java.awt.Color(249, 177, 122));
        AddUserBtn.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        AddUserBtn.setForeground(new java.awt.Color(66, 71, 105));
        AddUserBtn.setText("ADD");
        AddUserBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(249, 177, 122), 0, true));
        AddUserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddUserBtnActionPerformed(evt);
            }
        });
        userFormPanel.add(AddUserBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 410, 110, 40));

        jLabel8.setFont(new java.awt.Font("Candara", 1, 48)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(249, 177, 122));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Add User");
        userFormPanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 320, -1));

        BodyPanel.add(userFormPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, 520, 550));

        CloseBtn.setBackground(new java.awt.Color(45, 50, 80));
        CloseBtn.setFont(new java.awt.Font("Candara", 1, 36)); // NOI18N
        CloseBtn.setForeground(new java.awt.Color(249, 177, 122));
        CloseBtn.setText("x");
        CloseBtn.setToolTipText("");
        CloseBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(45, 50, 80), 0));
        CloseBtn.setBorderPainted(false);
        CloseBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CloseBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CloseBtnMouseExited(evt);
            }
        });
        CloseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseBtnActionPerformed(evt);
            }
        });
        BodyPanel.add(CloseBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 0, 50, 40));

        getContentPane().add(BodyPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1320, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CloseBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseBtnMouseEntered
        // TODO add your handling code here:
        CloseBtn.setBackground(new Color(249,177,122));
        CloseBtn.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_CloseBtnMouseEntered

    private void CloseBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseBtnMouseExited
        // TODO add your handling code here:
        CloseBtn.setBackground(new Color(66,71,105));
        CloseBtn.setForeground(new Color(249,177,122));
    }//GEN-LAST:event_CloseBtnMouseExited

    private void CloseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseBtnActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_CloseBtnActionPerformed

    private void AddUserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddUserBtnActionPerformed
        // TODO add your handling code here:
        String email = emailField.getText();
        char[] pwd = PasswordField.getPassword();
        String password = new String(pwd);
        
        
        
        if (validateEmail(email)) {
            System.out.println("Adresse e-mail valide.");
            if (validatePassword(password)) {
                System.out.println("Mot de passe valide.");
                
                BasicTextEncryptor textEncryptor = new BasicTextEncryptor();
        
                textEncryptor.setPassword("123");

                String encryptedPassword = textEncryptor.encrypt(password);

                Utilisateur utilisateur = new Utilisateur();

                utilisateur.setEmail(email);
                utilisateur.setPass(encryptedPassword);

                enregistrerUtilisateur(utilisateur);

                JOptionPane.showMessageDialog(this, "Utilisateur créé avec succès");

                this.dispose();
                new Signin().setVisible(true);

            } else {
                System.out.println("Mot de passe invalide.");
                JOptionPane.showMessageDialog(this, "Mot de passe invalide.");
            }
            
        } else {
            System.out.println("Adresse e-mail invalide.");
            JOptionPane.showMessageDialog(this, "Adresse e-mail invalide.");
        }
    }//GEN-LAST:event_AddUserBtnActionPerformed

    
    
    public static boolean validatePassword(String password) {
        String regex = "^(?=.*[A-Z])(?=.*[!@#$%^&*()-_+=])(?=.*\\d.*\\d)[A-Za-z!@#$%^&*()-_+=\\d]{8,}$";
        Pattern pattern = Pattern.compile(regex);
        Matcher matcher = pattern.matcher(password);
        return matcher.matches();
    }
    
    public static boolean validateEmail(String email) {
        String regex = "^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$";
        Pattern pattern = Pattern.compile(regex);
        Matcher matcher = pattern.matcher(email);
        return matcher.matches();
    }
    
    
    
       /**
     * Représente l'entity manager factory (unité de persistance)
     */
    private final EntityManagerFactory emf = javax.persistence.Persistence.createEntityManagerFactory("GestionNotesPU");
    /**
     * Représente l'entity manager pour effectuer les opérations sur les bases
     * de données
     */
    private final EntityManager entitymanager = emf.createEntityManager();
	
	 /*
     * Retourne la liste des étudiants
     * @return liste des etudiants
     */
    public List<Utilisateur> retourneUtilisateurs() {
       
        //Query jpql = entitymanager.createQuery("SELECT e FROM Etudiant e");
        Query jpql = entitymanager.createNamedQuery("Utilisateur.findAll");

        return jpql.getResultList();
    }

    /**
     * Enrégistrer un étudiant
     *
     * @param utilisateur
     */
    public void enregistrerUtilisateur(Utilisateur utilisateur) {
        entitymanager.getTransaction().begin();
        entitymanager.persist(utilisateur);
        entitymanager.getTransaction().commit();
      
    }
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    UIManager.setLookAndFeel(new FlatDarkLaf());
                } catch (UnsupportedLookAndFeelException e) {
                    e.printStackTrace();
                }
                
                
                new AddUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddUserBtn;
    private javax.swing.JPanel BodyPanel;
    private javax.swing.JButton CloseBtn;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JTextField emailField;
    private javax.swing.JTextField fullnameField;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JPanel userFormPanel;
    // End of variables declaration//GEN-END:variables
}
