/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gestionnotes;

import com.formdev.flatlaf.FlatDarkLaf;
import java.awt.Color;
import java.awt.Frame;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JFrame;
import javax.swing.Timer;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Lenovo
 */
public class bienvenue extends javax.swing.JFrame {

    /**
     * Creates new form bienvenue
     */
    public bienvenue() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        CloseBtn = new javax.swing.JButton();
        MinimiseBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(300, 190));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(45, 50, 80));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestionnotes/mm3.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 110, 290, 420));

        jLabel1.setFont(new java.awt.Font("Candara", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(249, 177, 122));
        jLabel1.setText("BIENVENUE");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 60, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestionnotes/1488 (1).gif"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 570, -1, -1));

        CloseBtn.setBackground(new java.awt.Color(45, 50, 80));
        CloseBtn.setFont(new java.awt.Font("Candara", 1, 36)); // NOI18N
        CloseBtn.setForeground(new java.awt.Color(249, 177, 122));
        CloseBtn.setText("x");
        CloseBtn.setToolTipText("");
        CloseBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(45, 50, 80), 0));
        CloseBtn.setBorderPainted(false);
        CloseBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CloseBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CloseBtnMouseExited(evt);
            }
        });
        CloseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseBtnActionPerformed(evt);
            }
        });
        jPanel1.add(CloseBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 0, 50, 40));

        MinimiseBtn.setBackground(new java.awt.Color(45, 50, 80));
        MinimiseBtn.setFont(new java.awt.Font("Candara", 1, 36)); // NOI18N
        MinimiseBtn.setForeground(new java.awt.Color(249, 177, 122));
        MinimiseBtn.setText("-");
        MinimiseBtn.setToolTipText("");
        MinimiseBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(45, 50, 80), 0));
        MinimiseBtn.setBorderPainted(false);
        MinimiseBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MinimiseBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MinimiseBtnMouseExited(evt);
            }
        });
        MinimiseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MinimiseBtnActionPerformed(evt);
            }
        });
        jPanel1.add(MinimiseBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 0, 50, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1320, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CloseBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseBtnMouseEntered
        // TODO add your handling code here:
        CloseBtn.setBackground(new Color(249,177,122));
        CloseBtn.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_CloseBtnMouseEntered

    private void CloseBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseBtnMouseExited
        // TODO add your handling code here:
        CloseBtn.setBackground(new Color(66,71,105));
        CloseBtn.setForeground(new Color(249,177,122));
    }//GEN-LAST:event_CloseBtnMouseExited

    private void CloseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseBtnActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_CloseBtnActionPerformed

    private void MinimiseBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimiseBtnMouseEntered
        // TODO add your handling code here:
        MinimiseBtn.setBackground(new Color(249,177,122));
        MinimiseBtn.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_MinimiseBtnMouseEntered

    private void MinimiseBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimiseBtnMouseExited
        // TODO add your handling code here:
        MinimiseBtn.setBackground(new Color(66,71,105));
        MinimiseBtn.setForeground(new Color(249,177,122));
    }//GEN-LAST:event_MinimiseBtnMouseExited

    private void MinimiseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MinimiseBtnActionPerformed
        // TODO add your handling code here:
        this.setState(Frame.ICONIFIED);
    }//GEN-LAST:event_MinimiseBtnActionPerformed

    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bienvenue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bienvenue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bienvenue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bienvenue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    UIManager.setLookAndFeel(new FlatDarkLaf());
                } catch (UnsupportedLookAndFeelException e) {
                    e.printStackTrace();
                }
                JFrame frame = new bienvenue();
                
                // Création d'un Timer qui se déclenchera après 5 secondes
                Timer timer;
                timer = new Timer(20000, new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        // Fermeture de la fenêtre lorsque le timer se déclenche
                        new Signin().setVisible(true);
                        frame.dispose();
                        ((Timer) e.getSource()).stop();
                    }
                });

                // Démarrage du timer
                timer.start();
                
                
                frame.setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CloseBtn;
    private javax.swing.JButton MinimiseBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
