/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gestionnotes;

import com.formdev.flatlaf.FlatDarkLaf;
import java.awt.Color;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Query;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author HP
 */
public class HomePage extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
    public HomePage() {
        initComponents();
        
        List<Etudiant> etudiants = retourneEtudiants();
        List<Departement> departements = retourneDepartements();
        List<Filiere> filieres = retourneFilieres();
        List<Specialite> specialites = retourneSpecialites();
        List<Promotion> promotions = retournePromotions();
        
        EtudiantNumber.setText(String.valueOf(etudiants.size()));
        DepartementNumber.setText(String.valueOf(departements.size()));
        FiliereNumber.setText(String.valueOf(filieres.size()));
        PromotionNumber.setText(String.valueOf(promotions.size()));
        SpecialiteNumber.setText(String.valueOf(specialites.size()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel2 = new javax.swing.JPanel();
        Specialite = new javax.swing.JButton();
        EtudiantBtn = new javax.swing.JButton();
        FilièreBtn = new javax.swing.JButton();
        DepartementBtn = new javax.swing.JButton();
        PromotionBtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        CloseBtn = new javax.swing.JButton();
        SpecialitePanel = new javax.swing.JPanel();
        SpecialiteNumber = new javax.swing.JLabel();
        SpecialiteLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        EtudiantPanel = new javax.swing.JPanel();
        EtudiantNumber = new javax.swing.JLabel();
        EtudiantLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        DepartementPanel = new javax.swing.JPanel();
        DepartementNumber = new javax.swing.JLabel();
        DepartementLabel = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        FilierePanel = new javax.swing.JPanel();
        FiliereNumber = new javax.swing.JLabel();
        FiliereLabel = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        PromotionPanel = new javax.swing.JPanel();
        PromotionNumber = new javax.swing.JLabel();
        PromotionLabel = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();

        jPanel2.setBackground(new java.awt.Color(66, 71, 105));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        Specialite.setBackground(new java.awt.Color(45, 50, 80));
        Specialite.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        Specialite.setForeground(new java.awt.Color(255, 255, 255));
        Specialite.setText("Gestion des Spécialités");
        Specialite.setBorder(null);
        Specialite.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Specialite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SpecialiteActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 150;
        gridBagConstraints.ipady = 25;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.weighty = 0.3;
        gridBagConstraints.insets = new java.awt.Insets(19, 24, 19, 24);
        jPanel2.add(Specialite, gridBagConstraints);

        EtudiantBtn.setBackground(new java.awt.Color(45, 50, 80));
        EtudiantBtn.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        EtudiantBtn.setForeground(new java.awt.Color(255, 255, 255));
        EtudiantBtn.setText("Gestion des Etudiants");
        EtudiantBtn.setBorder(null);
        EtudiantBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        EtudiantBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EtudiantBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 150;
        gridBagConstraints.ipady = 25;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.weighty = 0.3;
        gridBagConstraints.insets = new java.awt.Insets(19, 24, 19, 24);
        jPanel2.add(EtudiantBtn, gridBagConstraints);

        FilièreBtn.setBackground(new java.awt.Color(45, 50, 80));
        FilièreBtn.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        FilièreBtn.setForeground(new java.awt.Color(255, 255, 255));
        FilièreBtn.setText("Gestion des Filières");
        FilièreBtn.setBorder(null);
        FilièreBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        FilièreBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FilièreBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 150;
        gridBagConstraints.ipady = 25;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.weighty = 0.3;
        gridBagConstraints.insets = new java.awt.Insets(19, 24, 19, 24);
        jPanel2.add(FilièreBtn, gridBagConstraints);

        DepartementBtn.setBackground(new java.awt.Color(45, 50, 80));
        DepartementBtn.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        DepartementBtn.setForeground(new java.awt.Color(255, 255, 255));
        DepartementBtn.setText("Gestion des Departement");
        DepartementBtn.setBorder(null);
        DepartementBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DepartementBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DepartementBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 150;
        gridBagConstraints.ipady = 25;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.weighty = 0.3;
        gridBagConstraints.insets = new java.awt.Insets(19, 24, 19, 24);
        jPanel2.add(DepartementBtn, gridBagConstraints);

        PromotionBtn.setBackground(new java.awt.Color(45, 50, 80));
        PromotionBtn.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        PromotionBtn.setForeground(new java.awt.Color(255, 255, 255));
        PromotionBtn.setText("Gestion des Promotion");
        PromotionBtn.setBorder(null);
        PromotionBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PromotionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PromotionBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 150;
        gridBagConstraints.ipady = 25;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.weighty = 0.3;
        gridBagConstraints.insets = new java.awt.Insets(19, 24, 19, 24);
        jPanel2.add(PromotionBtn, gridBagConstraints);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(300, 190));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(66, 71, 105));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(249, 177, 122));
        jLabel1.setText("Logout");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, 30));

        CloseBtn.setBackground(new java.awt.Color(66, 71, 105));
        CloseBtn.setFont(new java.awt.Font("Candara", 1, 36)); // NOI18N
        CloseBtn.setForeground(new java.awt.Color(249, 177, 122));
        CloseBtn.setText("x");
        CloseBtn.setToolTipText("");
        CloseBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(66, 71, 105), 0));
        CloseBtn.setBorderPainted(false);
        CloseBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CloseBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CloseBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CloseBtnMouseExited(evt);
            }
        });
        CloseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseBtnActionPerformed(evt);
            }
        });
        jPanel1.add(CloseBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 0, 50, 40));

        SpecialitePanel.setBackground(new java.awt.Color(45, 50, 80));
        SpecialitePanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(45, 50, 80), 0, true));
        SpecialitePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SpecialitePanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SpecialitePanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SpecialitePanelMouseExited(evt);
            }
        });
        SpecialitePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SpecialiteNumber.setFont(new java.awt.Font("Candara", 1, 48)); // NOI18N
        SpecialiteNumber.setForeground(new java.awt.Color(255, 255, 255));
        SpecialiteNumber.setText("90");
        SpecialitePanel.add(SpecialiteNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        SpecialiteLabel.setFont(new java.awt.Font("Candara", 1, 36)); // NOI18N
        SpecialiteLabel.setForeground(new java.awt.Color(255, 255, 255));
        SpecialiteLabel.setText("Spécialité");
        SpecialitePanel.add(SpecialiteLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestionnotes/specialite.png"))); // NOI18N
        SpecialitePanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, -1, 80));

        jPanel7.setBackground(new java.awt.Color(45, 50, 80));
        jPanel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(45, 50, 80), 0, true));
        jPanel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel7MouseExited(evt);
            }
        });
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Candara", 1, 48)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("90");
        jPanel7.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jLabel15.setFont(new java.awt.Font("Candara", 1, 36)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Etudiants");
        jPanel7.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Desktop\\graduation-cap-solid (2).png")); // NOI18N
        jPanel7.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, -1, 80));

        SpecialitePanel.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 320, 280, 140));

        jPanel1.add(SpecialitePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 350, 320, 170));

        EtudiantPanel.setBackground(new java.awt.Color(45, 50, 80));
        EtudiantPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(45, 50, 80), 0, true));
        EtudiantPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EtudiantPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EtudiantPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                EtudiantPanelMouseExited(evt);
            }
        });
        EtudiantPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        EtudiantNumber.setFont(new java.awt.Font("Candara", 1, 48)); // NOI18N
        EtudiantNumber.setForeground(new java.awt.Color(255, 255, 255));
        EtudiantNumber.setText("90");
        EtudiantPanel.add(EtudiantNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        EtudiantLabel.setFont(new java.awt.Font("Candara", 1, 36)); // NOI18N
        EtudiantLabel.setForeground(new java.awt.Color(255, 255, 255));
        EtudiantLabel.setText("Etudiants");
        EtudiantPanel.add(EtudiantLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestionnotes/etudiant.png"))); // NOI18N
        EtudiantPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, -1, 80));

        jPanel1.add(EtudiantPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 310, 170));

        DepartementPanel.setBackground(new java.awt.Color(45, 50, 80));
        DepartementPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(45, 50, 80), 0, true));
        DepartementPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DepartementPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DepartementPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DepartementPanelMouseExited(evt);
            }
        });
        DepartementPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DepartementNumber.setFont(new java.awt.Font("Candara", 1, 48)); // NOI18N
        DepartementNumber.setForeground(new java.awt.Color(255, 255, 255));
        DepartementNumber.setText("90");
        DepartementPanel.add(DepartementNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        DepartementLabel.setFont(new java.awt.Font("Candara", 1, 36)); // NOI18N
        DepartementLabel.setForeground(new java.awt.Color(255, 255, 255));
        DepartementLabel.setText("Departement");
        DepartementPanel.add(DepartementLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestionnotes/departement.png"))); // NOI18N
        DepartementPanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, -1, 80));

        jPanel1.add(DepartementPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 90, 310, 170));

        FilierePanel.setBackground(new java.awt.Color(45, 50, 80));
        FilierePanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(45, 50, 80), 0, true));
        FilierePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FilierePanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                FilierePanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                FilierePanelMouseExited(evt);
            }
        });
        FilierePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        FiliereNumber.setFont(new java.awt.Font("Candara", 1, 48)); // NOI18N
        FiliereNumber.setForeground(new java.awt.Color(255, 255, 255));
        FiliereNumber.setText("90");
        FilierePanel.add(FiliereNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        FiliereLabel.setFont(new java.awt.Font("Candara", 1, 36)); // NOI18N
        FiliereLabel.setForeground(new java.awt.Color(255, 255, 255));
        FiliereLabel.setText("Filière");
        FilierePanel.add(FiliereLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestionnotes/filiere.png"))); // NOI18N
        FilierePanel.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 100, 80));

        jPanel1.add(FilierePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 90, 300, 170));

        PromotionPanel.setBackground(new java.awt.Color(45, 50, 80));
        PromotionPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(45, 50, 80), 0, true));
        PromotionPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PromotionPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PromotionPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PromotionPanelMouseExited(evt);
            }
        });
        PromotionPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PromotionNumber.setFont(new java.awt.Font("Candara", 1, 48)); // NOI18N
        PromotionNumber.setForeground(new java.awt.Color(255, 255, 255));
        PromotionNumber.setText("90");
        PromotionPanel.add(PromotionNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        PromotionLabel.setFont(new java.awt.Font("Candara", 1, 36)); // NOI18N
        PromotionLabel.setForeground(new java.awt.Color(255, 255, 255));
        PromotionLabel.setText("Promotion");
        PromotionPanel.add(PromotionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestionnotes/promo.png"))); // NOI18N
        PromotionPanel.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, -1, 80));

        jPanel9.setBackground(new java.awt.Color(45, 50, 80));
        jPanel9.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(45, 50, 80), 0, true));
        jPanel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel9MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel9MouseExited(evt);
            }
        });
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setFont(new java.awt.Font("Candara", 1, 48)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("90");
        jPanel9.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jLabel21.setFont(new java.awt.Font("Candara", 1, 36)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Etudiants");
        jPanel9.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel22.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Desktop\\graduation-cap-solid (2).png")); // NOI18N
        jPanel9.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, -1, 80));

        PromotionPanel.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 320, 280, 140));

        jPanel1.add(PromotionPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 350, 320, 170));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1320, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SpecialiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SpecialiteActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new EtudiantForm().setVisible(true);
    }//GEN-LAST:event_SpecialiteActionPerformed

    private void EtudiantBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EtudiantBtnActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new EtudiantForm().setVisible(true);
    }//GEN-LAST:event_EtudiantBtnActionPerformed

    private void FilièreBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FilièreBtnActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new FiliereForm().setVisible(true);

    }//GEN-LAST:event_FilièreBtnActionPerformed

    private void DepartementBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DepartementBtnActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new DepartementForm().setVisible(true);
    }//GEN-LAST:event_DepartementBtnActionPerformed

    private void PromotionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PromotionBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PromotionBtnActionPerformed

    private void CloseBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseBtnMouseEntered
        // TODO add your handling code here:
        CloseBtn.setBackground(new Color(249,177,122));
        CloseBtn.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_CloseBtnMouseEntered

    private void CloseBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseBtnMouseExited
        // TODO add your handling code here:
        CloseBtn.setBackground(new Color(66,71,105));
        CloseBtn.setForeground(new Color(249,177,122));
    }//GEN-LAST:event_CloseBtnMouseExited

    private void CloseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseBtnActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_CloseBtnActionPerformed

    private void SpecialitePanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SpecialitePanelMouseEntered
        // TODO add your handling code here:
        SpecialitePanel.setBackground(new Color(249,177,122));
        SpecialiteNumber.setForeground(new Color(45,50,80));
        SpecialiteLabel.setForeground(new Color(45,50,80));

    }//GEN-LAST:event_SpecialitePanelMouseEntered

    private void SpecialitePanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SpecialitePanelMouseExited
        // TODO add your handling code here:
        SpecialitePanel.setBackground(new Color(45,50,80));
        SpecialiteNumber.setForeground(new Color(255,255,255));
        SpecialiteLabel.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_SpecialitePanelMouseExited

    private void SpecialitePanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SpecialitePanelMouseClicked
        // TODO add your handling code here:
        this.dispose();
        new SpecialiteForm().setVisible(true);
    }//GEN-LAST:event_SpecialitePanelMouseClicked

    private void EtudiantPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EtudiantPanelMouseClicked
        // TODO add your handling code here:
        this.dispose();
        new EtudiantForm().setVisible(true);
    }//GEN-LAST:event_EtudiantPanelMouseClicked

    private void EtudiantPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EtudiantPanelMouseEntered
        // TODO add your handling code here:
        EtudiantPanel.setBackground(new Color(249,177,122));
        EtudiantNumber.setForeground(new Color(45,50,80));
        EtudiantLabel.setForeground(new Color(45,50,80));
    }//GEN-LAST:event_EtudiantPanelMouseEntered

    private void EtudiantPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EtudiantPanelMouseExited
        // TODO add your handling code here:
        EtudiantPanel.setBackground(new Color(45,50,80));
        EtudiantNumber.setForeground(new Color(255,255,255));
        EtudiantLabel.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_EtudiantPanelMouseExited

    private void DepartementPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DepartementPanelMouseClicked
        // TODO add your handling code here:
        this.dispose();
        new DepartementForm().setVisible(true);
    }//GEN-LAST:event_DepartementPanelMouseClicked

    private void DepartementPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DepartementPanelMouseEntered
        // TODO add your handling code here:
        DepartementPanel.setBackground(new Color(249,177,122));
        DepartementNumber.setForeground(new Color(45,50,80));
        DepartementLabel.setForeground(new Color(45,50,80));
    }//GEN-LAST:event_DepartementPanelMouseEntered

    private void DepartementPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DepartementPanelMouseExited
        // TODO add your handling code here:
        DepartementPanel.setBackground(new Color(45,50,80));
        DepartementNumber.setForeground(new Color(255,255,255));
        DepartementLabel.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_DepartementPanelMouseExited

    private void FilierePanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FilierePanelMouseClicked
        // TODO add your handling code here:
        this.dispose();
        new FiliereForm().setVisible(true);
    }//GEN-LAST:event_FilierePanelMouseClicked

    private void FilierePanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FilierePanelMouseEntered
        // TODO add your handling code here:
        FilierePanel.setBackground(new Color(249,177,122));
        FiliereNumber.setForeground(new Color(45,50,80));
        FiliereLabel.setForeground(new Color(45,50,80));
    }//GEN-LAST:event_FilierePanelMouseEntered

    private void FilierePanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FilierePanelMouseExited
        // TODO add your handling code here:
        FilierePanel.setBackground(new Color(45,50,80));
        FiliereNumber.setForeground(new Color(255,255,255));
        FiliereLabel.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_FilierePanelMouseExited

    private void jPanel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel7MouseClicked

    private void jPanel7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MouseEntered
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jPanel7MouseEntered

    private void jPanel7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel7MouseExited

    private void jPanel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel9MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel9MouseClicked

    private void jPanel9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel9MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel9MouseEntered

    private void jPanel9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel9MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel9MouseExited

    private void PromotionPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PromotionPanelMouseClicked
        // TODO add your handling code here:
        this.dispose();
        new PromotionForm().setVisible(true);
    }//GEN-LAST:event_PromotionPanelMouseClicked

    private void PromotionPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PromotionPanelMouseEntered
        // TODO add your handling code here:
        PromotionPanel.setBackground(new Color(249,177,122));
        PromotionNumber.setForeground(new Color(45,50,80));
        PromotionLabel.setForeground(new Color(45,50,80));
    }//GEN-LAST:event_PromotionPanelMouseEntered

    private void PromotionPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PromotionPanelMouseExited
        // TODO add your handling code here:
        PromotionPanel.setBackground(new Color(45,50,80));
        PromotionNumber.setForeground(new Color(255,255,255));
        PromotionLabel.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_PromotionPanelMouseExited

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        new Signin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    
    
    
    
    /**
     * Représente l'entity manager factory (unité de persistance)
     */
    private final EntityManagerFactory emf = javax.persistence.Persistence.createEntityManagerFactory("GestionNotesPU");
    /**
     * Représente l'entity manager pour effectuer les opérations sur les bases
     * de données
     */
    private final EntityManager entitymanager = emf.createEntityManager();
	
    /**
     * Retourne la liste des étudiants
     * @return liste des etudiants
     */
    private List<Etudiant> retourneEtudiants() {
       
        //Query jpql = entitymanager.createQuery("SELECT e FROM Etudiant e");
        Query jpql = entitymanager.createNamedQuery("Etudiant.findAll");

        return jpql.getResultList();
    }
    
    /**
     * Retourne la liste des Departements
     * @return liste des Departements
     */
    private List<Departement> retourneDepartements() {
       
        //Query jpql = entitymanager.createQuery("SELECT e FROM Departement e");
        Query jpql = entitymanager.createNamedQuery("Departement.findAll");

        return jpql.getResultList();
    }
    
    private List<Filiere> retourneFilieres() {
        Query jpql = entitymanager.createNamedQuery("Filiere.findAll");

        return jpql.getResultList();
    }
    
    /**
     * Retourne la liste des Formations
     * @return liste des formation
     */
    private List<Promotion> retournePromotions() {
        Query jpql = entitymanager.createNamedQuery("Promotion.findAll");

        return jpql.getResultList();
    }

    private List<Specialite> retourneSpecialites() {
        Query jpql = entitymanager.createNamedQuery("Specialite.findAll");

        return jpql.getResultList();
    }
    
    
    
    
    
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    UIManager.setLookAndFeel(new FlatDarkLaf());
                } catch (UnsupportedLookAndFeelException e) {
                    e.printStackTrace();
                }
                new HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CloseBtn;
    private javax.swing.JButton DepartementBtn;
    private javax.swing.JLabel DepartementLabel;
    private javax.swing.JLabel DepartementNumber;
    private javax.swing.JPanel DepartementPanel;
    private javax.swing.JButton EtudiantBtn;
    private javax.swing.JLabel EtudiantLabel;
    private javax.swing.JLabel EtudiantNumber;
    private javax.swing.JPanel EtudiantPanel;
    private javax.swing.JLabel FiliereLabel;
    private javax.swing.JLabel FiliereNumber;
    private javax.swing.JPanel FilierePanel;
    private javax.swing.JButton FilièreBtn;
    private javax.swing.JButton PromotionBtn;
    private javax.swing.JLabel PromotionLabel;
    private javax.swing.JLabel PromotionNumber;
    private javax.swing.JPanel PromotionPanel;
    private javax.swing.JButton Specialite;
    private javax.swing.JLabel SpecialiteLabel;
    private javax.swing.JLabel SpecialiteNumber;
    private javax.swing.JPanel SpecialitePanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    // End of variables declaration//GEN-END:variables
}
