/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gestionnotes;

import com.formdev.flatlaf.FlatDarkLaf;
import java.awt.Color;
import java.awt.Frame;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Query;
import javax.swing.RowFilter;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.event.ListSelectionEvent;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import javax.swing.text.AbstractDocument;

/**
 *
 * @author HP
 */
public class PromotionForm extends javax.swing.JFrame {

    
    int idSelectedLigne;
    /**
     * Creates new form PromotionForm
     */
    public PromotionForm() {
        initComponents();
                
        ((AbstractDocument) PromotionAnneeField.getDocument()).setDocumentFilter(new NumericFilter());

        AfficherTable();
        SelectionnerLigne();
        Recherche();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EtuFormPanel1 = new javax.swing.JPanel();
        PromotionAnneeField = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        PromotionAnneeLabel = new javax.swing.JLabel();
        addBtn1 = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        editBtn = new javax.swing.JButton();
        titleLabel = new javax.swing.JLabel();
        HomeBtn = new javax.swing.JLabel();
        EtuTablePanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        PromotionTable = new javax.swing.JTable();
        searchField = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        rechercheLabel = new javax.swing.JLabel();
        CloseBtn = new javax.swing.JButton();
        MinimiseBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(300, 190));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        EtuFormPanel1.setBackground(new java.awt.Color(45, 50, 80));
        EtuFormPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PromotionAnneeField.setBackground(new java.awt.Color(45, 50, 80));
        PromotionAnneeField.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        PromotionAnneeField.setForeground(new java.awt.Color(255, 255, 255));
        PromotionAnneeField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        PromotionAnneeField.setCaretColor(new java.awt.Color(255, 255, 255));
        EtuFormPanel1.add(PromotionAnneeField, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 350, 40));

        jSeparator2.setBackground(new java.awt.Color(249, 177, 122));
        jSeparator2.setForeground(new java.awt.Color(249, 177, 122));
        EtuFormPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 350, 10));

        PromotionAnneeLabel.setBackground(new java.awt.Color(249, 177, 122));
        PromotionAnneeLabel.setFont(new java.awt.Font("Candara", 1, 16)); // NOI18N
        PromotionAnneeLabel.setForeground(new java.awt.Color(249, 177, 122));
        PromotionAnneeLabel.setText("Année");
        EtuFormPanel1.add(PromotionAnneeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, -1));

        addBtn1.setBackground(new java.awt.Color(51, 51, 255));
        addBtn1.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        addBtn1.setForeground(new java.awt.Color(255, 255, 255));
        addBtn1.setText("ADD");
        addBtn1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true));
        addBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtn1ActionPerformed(evt);
            }
        });
        EtuFormPanel1.add(addBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 90, 30));

        deleteBtn.setBackground(new java.awt.Color(255, 102, 102));
        deleteBtn.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        deleteBtn.setForeground(new java.awt.Color(255, 255, 255));
        deleteBtn.setText("DELETE");
        deleteBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true));
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });
        EtuFormPanel1.add(deleteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 340, 90, 30));

        editBtn.setBackground(new java.awt.Color(255, 204, 0));
        editBtn.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        editBtn.setForeground(new java.awt.Color(255, 255, 255));
        editBtn.setText("EDIT");
        editBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true));
        editBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtnActionPerformed(evt);
            }
        });
        EtuFormPanel1.add(editBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, 90, 30));

        titleLabel.setBackground(new java.awt.Color(249, 177, 122));
        titleLabel.setFont(new java.awt.Font("Candara", 1, 36)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(249, 177, 122));
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Gestion Des Promotions");
        EtuFormPanel1.add(titleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        HomeBtn.setForeground(new java.awt.Color(249, 177, 122));
        HomeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestionnotes/home.png"))); // NOI18N
        HomeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeBtnMouseClicked(evt);
            }
        });
        EtuFormPanel1.add(HomeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(EtuFormPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 700));

        EtuTablePanel.setBackground(new java.awt.Color(66, 71, 105));
        EtuTablePanel.setForeground(new java.awt.Color(255, 255, 255));
        EtuTablePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBackground(new java.awt.Color(66, 71, 105));
        jScrollPane1.setForeground(new java.awt.Color(255, 255, 255));

        PromotionTable.setBackground(new java.awt.Color(66, 71, 105));
        PromotionTable.setFont(new java.awt.Font("Candara", 0, 15)); // NOI18N
        PromotionTable.setForeground(new java.awt.Color(255, 255, 255));
        PromotionTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        PromotionTable.setShowHorizontalLines(true);
        jScrollPane1.setViewportView(PromotionTable);

        EtuTablePanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 830, 580));

        searchField.setBackground(new java.awt.Color(66, 71, 105));
        searchField.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        searchField.setForeground(new java.awt.Color(255, 255, 255));
        searchField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        searchField.setCaretColor(new java.awt.Color(255, 255, 255));
        EtuTablePanel.add(searchField, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 60, 300, 40));

        jSeparator6.setBackground(new java.awt.Color(249, 177, 122));
        jSeparator6.setForeground(new java.awt.Color(249, 177, 122));
        EtuTablePanel.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 100, 300, 20));

        rechercheLabel.setBackground(new java.awt.Color(249, 177, 122));
        rechercheLabel.setFont(new java.awt.Font("Candara", 1, 16)); // NOI18N
        rechercheLabel.setForeground(new java.awt.Color(249, 177, 122));
        rechercheLabel.setText("Rechercher");
        EtuTablePanel.add(rechercheLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, -1, -1));

        CloseBtn.setBackground(new java.awt.Color(66, 71, 105));
        CloseBtn.setFont(new java.awt.Font("Candara", 1, 36)); // NOI18N
        CloseBtn.setForeground(new java.awt.Color(249, 177, 122));
        CloseBtn.setText("x");
        CloseBtn.setToolTipText("");
        CloseBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(66, 71, 105), 0));
        CloseBtn.setBorderPainted(false);
        CloseBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CloseBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CloseBtnMouseExited(evt);
            }
        });
        CloseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseBtnActionPerformed(evt);
            }
        });
        EtuTablePanel.add(CloseBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 0, 50, 40));

        MinimiseBtn.setBackground(new java.awt.Color(66, 71, 105));
        MinimiseBtn.setFont(new java.awt.Font("Candara", 1, 36)); // NOI18N
        MinimiseBtn.setForeground(new java.awt.Color(249, 177, 122));
        MinimiseBtn.setText("-");
        MinimiseBtn.setToolTipText("");
        MinimiseBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(66, 71, 105), 0));
        MinimiseBtn.setBorderPainted(false);
        MinimiseBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinimiseBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MinimiseBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MinimiseBtnMouseExited(evt);
            }
        });
        MinimiseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MinimiseBtnActionPerformed(evt);
            }
        });
        EtuTablePanel.add(MinimiseBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 0, 50, 40));

        getContentPane().add(EtuTablePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, 830, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtn1ActionPerformed
        // TODO add your handling code here:
        String nom = PromotionAnneeField.getText();
        
        Promotion promotion = new Promotion();
        promotion.setAnnee(nom);

        enregistrerPromotion(promotion);
        AfficherTable();
        ResetForm();
    }//GEN-LAST:event_addBtn1ActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
        int promotionToBeModifiedId = getIdSelected();

        Promotion promotion = retournePromotion(promotionToBeModifiedId);
        
        DeletePromotion(promotion);
        
        ResetForm();
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
        // TODO add your handling code here:
        String nom = PromotionAnneeField.getText();
        int promotiontToBeModifiedId = getIdSelected();
        Promotion promotion = retournePromotion(promotiontToBeModifiedId);
        promotion.setAnnee(nom);

        UpdatePromotion(promotion);
        ResetForm();
        AfficherTable();
    }//GEN-LAST:event_editBtnActionPerformed

    private void CloseBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseBtnMouseEntered
        // TODO add your handling code here:
        CloseBtn.setBackground(new Color(249,177,122));
        CloseBtn.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_CloseBtnMouseEntered

    private void CloseBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseBtnMouseExited
        // TODO add your handling code here:
        CloseBtn.setBackground(new Color(66,71,105));
        CloseBtn.setForeground(new Color(249,177,122));
    }//GEN-LAST:event_CloseBtnMouseExited

    private void CloseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseBtnActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_CloseBtnActionPerformed

    private void HomeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeBtnMouseClicked
        // TODO add your handling code here:
        new HomePage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_HomeBtnMouseClicked

    private void MinimiseBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimiseBtnMouseClicked
        // TODO add your handling code here:
        this.setState(Frame.ICONIFIED);
    }//GEN-LAST:event_MinimiseBtnMouseClicked

    private void MinimiseBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimiseBtnMouseEntered
        // TODO add your handling code here:
        MinimiseBtn.setBackground(new Color(249,177,122));
        MinimiseBtn.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_MinimiseBtnMouseEntered

    private void MinimiseBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimiseBtnMouseExited
        // TODO add your handling code here:
        MinimiseBtn.setBackground(new Color(66,71,105));
        MinimiseBtn.setForeground(new Color(249,177,122));
    }//GEN-LAST:event_MinimiseBtnMouseExited

    private void MinimiseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MinimiseBtnActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_MinimiseBtnActionPerformed

        private void AfficherTable() {        
        List<Promotion> promotions = retournePromotions();   

        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("N°");
        model.addColumn("Année ");

        for (Promotion promotion : promotions){
            Object[] rowData = {promotion.getIdPromotion(), promotion.getAnnee()};
            model.addRow(rowData);
        }
        
        PromotionTable.setModel(model);
    }
    
    private void SelectionnerLigne() {
        PromotionTable.getSelectionModel().addListSelectionListener((ListSelectionEvent e) -> {
            if (!e.getValueIsAdjusting()) {
                int selectedRow = PromotionTable.getSelectedRow();

                System.out.println(selectedRow);
                if (selectedRow != -1) {
                    // Récupérer les éléments de la ligne sélectionnée
                    int id = Integer.parseInt(PromotionTable.getValueAt(selectedRow, 0).toString());
                    String nom = PromotionTable.getValueAt(selectedRow, 1).toString();

                    // Afficher les éléments récupérés dans le formulaire
                    PromotionAnneeField.setText(nom);
                    
                    idSelectedLigne = id;
                }
            }
        });   
    }
    
    public int getIdSelected() {
        return idSelectedLigne;
    }
    
    public void ResetForm() {
        PromotionAnneeField.setText("");
    }
    
    
    private void Recherche() {
        TableRowSorter<TableModel> sort = new TableRowSorter<>(PromotionTable.getModel());
        PromotionTable.setRowSorter(sort);
        
        searchField.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                String str = searchField.getText();
                if (str.trim().length() == 0) {
                    sort.setRowFilter(null);
                } else {
                    // Échappez les caractères spéciaux dans la chaîne de recherche
                    String escapedStr = java.util.regex.Pattern.quote(str);
                    sort.setRowFilter(RowFilter.regexFilter("(?i)" + escapedStr));
                }
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                String str = searchField.getText();
                if (str.trim().length() == 0) {
                    sort.setRowFilter(null);
                } else {
                    // Échappez les caractères spéciaux dans la chaîne de recherche
                    String escapedStr = java.util.regex.Pattern.quote(str);
                    sort.setRowFilter(RowFilter.regexFilter("(?i)" + escapedStr));
                }
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                
            }
        
        });
    }
    
    
    /**
     * Représente l'entity manager factory (unité de persistance)
     */
    private final EntityManagerFactory emf = javax.persistence.Persistence.createEntityManagerFactory("GestionNotesPU");
    /**
     * Représente l'entity manager pour effectuer les opérations sur les bases
     * de données
     */
    private final EntityManager entitymanager = emf.createEntityManager();
	
    /**
     * Retourne la liste des Formations
     * @return liste des formation
     */
    public List<Promotion> retournePromotions() {
        Query jpql = entitymanager.createNamedQuery("Promotion.findAll");

        return jpql.getResultList();
    }

       /**
     * Retourne la filiere
     * @param id
     * @return
     */
    public Promotion retournePromotion(int id) {
        // Utilisation de la requête nommée "Promotion.findById"
        Query query = entitymanager.createNamedQuery("Promotion.findByIdPromotion");
        query.setParameter("idPromotion", id);

        // Exécution de la requête
        return (Promotion) query.getSingleResult();
    }

    /**
     * Enrégistrer une filiere
     *
     * @param promotion
     */
    public void enregistrerPromotion(Promotion promotion) {
        entitymanager.getTransaction().begin();
        entitymanager.persist(promotion);
        entitymanager.getTransaction().commit();
      
    }
    
    public void UpdatePromotion(Promotion promotion) {
        entitymanager.getTransaction().begin();
        entitymanager.merge(promotion);
        entitymanager.getTransaction().commit();
    }
    
    public void DeletePromotion(Promotion promotion) {
        entitymanager.getTransaction().begin();
        entitymanager.remove(promotion);
        entitymanager.getTransaction().commit();
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PromotionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PromotionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PromotionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PromotionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    UIManager.setLookAndFeel(new FlatDarkLaf());
                } catch (UnsupportedLookAndFeelException e) {
                    e.printStackTrace();
                }
                new PromotionForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CloseBtn;
    private javax.swing.JPanel EtuFormPanel1;
    private javax.swing.JPanel EtuTablePanel;
    private javax.swing.JLabel HomeBtn;
    private javax.swing.JButton MinimiseBtn;
    private javax.swing.JTextField PromotionAnneeField;
    private javax.swing.JLabel PromotionAnneeLabel;
    private javax.swing.JTable PromotionTable;
    private javax.swing.JButton addBtn1;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton editBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel rechercheLabel;
    private javax.swing.JTextField searchField;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
