/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gestionnotes;

import com.formdev.flatlaf.FlatDarkLaf;
import java.awt.Color;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Query;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import org.jasypt.util.text.BasicTextEncryptor;


/**
 *
 * @author HP
 */
public class Signin extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Signin() {
        initComponents();
        Overlay.setBackground(new Color(45,50,80,50));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SignInForm = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        emailField = new javax.swing.JTextField();
        PasswordField = new javax.swing.JPasswordField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        SignUpBtn = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        CloseBtn = new javax.swing.JButton();
        Overlay = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));
        setLocation(new java.awt.Point(300, 190));
        setMinimumSize(new java.awt.Dimension(1320, 700));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SignInForm.setBackground(new java.awt.Color(45, 50, 80));
        SignInForm.setMinimumSize(new java.awt.Dimension(600, 700));
        SignInForm.setPreferredSize(new java.awt.Dimension(600, 700));
        SignInForm.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Candara", 1, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Don't have an account ?");
        SignInForm.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 540, 150, -1));

        jSeparator2.setBackground(new java.awt.Color(249, 177, 122));
        jSeparator2.setForeground(new java.awt.Color(249, 177, 122));
        SignInForm.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 390, -1));

        emailField.setBackground(new java.awt.Color(45, 50, 80));
        emailField.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        emailField.setForeground(new java.awt.Color(57, 113, 177));
        emailField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        emailField.setCaretColor(new java.awt.Color(255, 255, 255));
        emailField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailFieldActionPerformed(evt);
            }
        });
        SignInForm.add(emailField, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 390, 40));

        PasswordField.setBackground(new java.awt.Color(45, 50, 80));
        PasswordField.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        PasswordField.setForeground(new java.awt.Color(57, 113, 177));
        PasswordField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        PasswordField.setCaretColor(new java.awt.Color(255, 255, 255));
        SignInForm.add(PasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 390, 40));

        jSeparator3.setBackground(new java.awt.Color(249, 177, 122));
        jSeparator3.setForeground(new java.awt.Color(249, 177, 122));
        SignInForm.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, 390, -1));

        jLabel3.setFont(new java.awt.Font("Candara", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(249, 177, 122));
        jLabel3.setText("Email");
        SignInForm.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 130, -1));

        jLabel4.setFont(new java.awt.Font("Candara", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(249, 177, 122));
        jLabel4.setText("Password");
        SignInForm.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, 150, -1));

        SignUpBtn.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        SignUpBtn.setForeground(new java.awt.Color(249, 177, 122));
        SignUpBtn.setText("Sign Up");
        SignUpBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SignUpBtnMouseClicked(evt);
            }
        });
        SignInForm.add(SignUpBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 540, 60, 20));

        jButton1.setBackground(new java.awt.Color(249, 177, 122));
        jButton1.setFont(new java.awt.Font("Candara", 1, 16)); // NOI18N
        jButton1.setForeground(new java.awt.Color(45, 50, 80));
        jButton1.setText("Sign Up");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(249, 177, 122), 0, true));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        SignInForm.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 400, 110, 30));

        jLabel11.setFont(new java.awt.Font("Candara", 1, 48)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(249, 177, 122));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Sign In");
        SignInForm.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 320, -1));

        CloseBtn.setBackground(new java.awt.Color(45, 50, 80));
        CloseBtn.setFont(new java.awt.Font("Candara", 1, 36)); // NOI18N
        CloseBtn.setForeground(new java.awt.Color(249, 177, 122));
        CloseBtn.setText("x");
        CloseBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(45, 50, 80), 0, true));
        CloseBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CloseBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CloseBtnMouseExited(evt);
            }
        });
        CloseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseBtnActionPerformed(evt);
            }
        });
        SignInForm.add(CloseBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 0, 50, 50));

        getContentPane().add(SignInForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 0, 620, 710));

        Overlay.setBackground(new java.awt.Color(0, 0, 0));
        Overlay.setMinimumSize(new java.awt.Dimension(500, 700));
        Overlay.setPreferredSize(new java.awt.Dimension(500, 700));
        Overlay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                OverlayMousePressed(evt);
            }
        });
        Overlay.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Vivaldi", 0, 48)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(249, 177, 122));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Welcome Back");
        Overlay.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 350, -1));

        jLabel9.setFont(new java.awt.Font("Candara", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Please Sign In");
        Overlay.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, 100, -1));

        getContentPane().add(Overlay, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 710));

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Downloads\\blabl.jpg")); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
                                                                               
    private void OverlayMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OverlayMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_OverlayMousePressed

    private void emailFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailFieldActionPerformed

    private void CloseBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseBtnMouseEntered
        // TODO add your handling code here:
        CloseBtn.setBackground(new Color(249,177,122));
        CloseBtn.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_CloseBtnMouseEntered

    private void CloseBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseBtnMouseExited
        // TODO add your handling code here:$
        CloseBtn.setBackground(new Color(66,71,105));
        CloseBtn.setForeground(new Color(249,177,122));
    }//GEN-LAST:event_CloseBtnMouseExited

    private void CloseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseBtnActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_CloseBtnActionPerformed

    private void SignUpBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignUpBtnMouseClicked
        // TODO add your handling code here:
        
        new AddUser().setVisible(true);
        
        this.dispose();

        
    }//GEN-LAST:event_SignUpBtnMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String email = emailField.getText();
        char[] pwd = PasswordField.getPassword();
        String password = new String(pwd);
        
        BasicTextEncryptor textEncryptor = new BasicTextEncryptor();
        
        textEncryptor.setPassword("123");
        
        String encryptedPassword = textEncryptor.encrypt(password);
        
        List<Utilisateur> utilisateurs = retourneUtilisateurs();
        
        for (Utilisateur utilisateur : utilisateurs) {
            if (utilisateur.getEmail().equals(email)) {
                if (textEncryptor.decrypt(utilisateur.getPass()).equals(password)){
//                    JOptionPane.showMessageDialog(this, "Utilisateur créé avec succès");
                    new HomePage().setVisible(true);
                    this.dispose();
                    break;
                } else {
                    JOptionPane.showMessageDialog(this, "Informations incorrect");
                    System.out.println(textEncryptor.decrypt(utilisateur.getPass()));
                    System.out.println(password);
                }
            } 
        }
        //JOptionPane.showMessageDialog(this, "Utilisateur introuvable");
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    
    
    
    
         /**
     * Représente l'entity manager factory (unité de persistance)
     */
    private final EntityManagerFactory emf = javax.persistence.Persistence.createEntityManagerFactory("GestionNotesPU");
    /**
     * Représente l'entity manager pour effectuer les opérations sur les bases
     * de données
     */
    private final EntityManager entitymanager = emf.createEntityManager();
	
	 /*
     * Retourne la liste des étudiants
     * @return liste des etudiants
     */
    public List<Utilisateur> retourneUtilisateurs() {
       
        //Query jpql = entitymanager.createQuery("SELECT e FROM Etudiant e");
        Query jpql = entitymanager.createNamedQuery("Utilisateur.findAll");

        return jpql.getResultList();
    }
    
    public Utilisateur retourneUtilisateur(int id) {
            // Utilisation de la requête nommée "Utilisateur.findById"
            Query query = entitymanager.createNamedQuery("Utilisateur.findById");
            query.setParameter("id", id);

            // Exécution de la requête
            return (Utilisateur) query.getSingleResult();
    }

    /**
     * Enrégistrer un étudiant
     *
     * @param utilisateur
     */
    public void enregistrerUtilisateur(Utilisateur utilisateur) {
        entitymanager.getTransaction().begin();
        entitymanager.persist(utilisateur);
        entitymanager.getTransaction().commit();
      
    }
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Signin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Signin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Signin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Signin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                try {
                    UIManager.setLookAndFeel(new FlatDarkLaf());
                } catch (UnsupportedLookAndFeelException e) {
                    e.printStackTrace();
                }
                
                Signin home = new Signin();
                home.setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CloseBtn;
    private javax.swing.JPanel Overlay;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JPanel SignInForm;
    private javax.swing.JLabel SignUpBtn;
    private javax.swing.JTextField emailField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables
}
